// Embedded from models/p37_radar/spec.json (the modelgen source of truth) so the game bundles the
// model with no runtime fetch / no dependency on models/ shipping. Built via the /modelgen harness.
// Keep in sync with models/p37_radar/spec.json if that spec changes (needs[]/dossier dropped — not used at runtime).
export const P37_RADAR_SPEC = {
  "id": "p37_radar",
  "name": "P-37 «Bar Lock» (П-37) — Soviet 2D E/F-band GCI / air-surveillance radar",
  "category": "industrial",
  "target": "voxel",
  "anchor": "floor",
  "footprint": { "w": 9.7, "h": 7.8, "d": 7.6 },
  "rig": [
    { "name": "azimuth",   "pivot": [0, 1.55, 0],   "axis": "y", "pose": 0,      "type": "spin",  "range": [0, 6.2832] },
    { "name": "frontTilt", "pivot": [0, 4.0, 2.7],   "axis": "x", "pose": 0.20,  "parent": "azimuth", "type": "fixed" },
    { "name": "rearTilt",  "pivot": [0, 6.0, -1.6],  "axis": "x", "pose": -0.785, "parent": "azimuth", "type": "fixed" }
  ],
  "parts": [
    { "op": "bevelBox", "id": "bed",       "args": { "w": 2.8, "h": 0.5, "d": 5.4 }, "at": [0, 1.15, 0], "mat": "oliveDrab", "src": "dossier#mount" },
    { "op": "bevelBox", "id": "subframe",  "args": { "w": 2.5, "h": 0.26, "d": 5.0 }, "at": [0, 0.84, 0], "mat": "gunGrey", "src": "dossier#mount" },
    { "op": "pipe", "id": "frameXa", "args": { "r": 0.05, "pts": [[-1.15, 0.92, 1.6], [1.15, 0.92, -1.6]], "tone": "lo" }, "at": [0, 0, 0], "mat": "gunGrey", "src": "dossier#mount" },
    { "op": "pipe", "id": "frameXb", "args": { "r": 0.05, "pts": [[1.15, 0.92, 1.6], [-1.15, 0.92, -1.6]], "tone": "lo" }, "at": [0, 0, 0], "mat": "gunGrey", "src": "dossier#mount" },
    { "op": "pipe", "id": "frameDa", "args": { "r": 0.05, "pts": [[-0.95, 0.95, 1.7], [0, 0.98, 3.0]], "tone": "lo" }, "at": [0, 0, 0], "mat": "gunGrey", "src": "dossier#mount" },
    { "op": "pipe", "id": "frameDb", "args": { "r": 0.05, "pts": [[0.95, 0.95, 1.7], [0, 0.98, 3.0]], "tone": "lo" }, "at": [0, 0, 0], "mat": "gunGrey", "src": "dossier#mount" },
    { "op": "bevelBox", "id": "drawbar",   "args": { "w": 0.32, "h": 0.28, "d": 2.2 }, "at": [0, 0.98, 3.5], "mat": "gunGrey", "src": "dossier#mount" },
    { "op": "cylinder", "id": "towEye",    "args": { "r": 0.17, "h": 0.16, "axis": "z", "tone": "hi" }, "at": [0, 0.98, 4.65], "mat": "gunGrey", "src": "dossier#mount" },
    { "op": "cylinder", "id": "noseJack",  "args": { "r": 0.08, "h": 1.0, "axis": "y", "tone": "lo" }, "at": [0, 0.5, 3.95], "mat": "steel", "src": "dossier#mount" },
    { "op": "cylinder", "id": "noseJackPad","args": { "r": 0.3, "h": 0.1, "axis": "y" }, "at": [0, 0.04, 3.95], "mat": "oliveDrab", "src": "dossier#mount" },

    { "op": "wheel", "id": "wheelFL", "args": { "r": 0.62, "w": 0.55, "axis": "x", "lugs": 8 }, "at": [-1.5, 0.62, 1.55], "mat": "tyre", "src": "dossier#mount" },
    { "op": "wheel", "id": "wheelFR", "args": { "r": 0.62, "w": 0.55, "axis": "x", "lugs": 8 }, "at": [1.5, 0.62, 1.55], "mat": "tyre", "src": "dossier#mount" },
    { "op": "wheel", "id": "wheelRL", "args": { "r": 0.62, "w": 0.55, "axis": "x", "lugs": 8 }, "at": [-1.5, 0.62, -1.55], "mat": "tyre", "src": "dossier#mount" },
    { "op": "wheel", "id": "wheelRR", "args": { "r": 0.62, "w": 0.55, "axis": "x", "lugs": 8 }, "at": [1.5, 0.62, -1.55], "mat": "tyre", "src": "dossier#mount" },
    { "op": "bevelBox", "id": "fenderFL", "args": { "w": 0.95, "h": 0.14, "d": 1.6 }, "at": [-1.5, 1.5, 1.55], "mat": "oliveDrab", "src": "dossier#mount" },
    { "op": "bevelBox", "id": "fenderFR", "args": { "w": 0.95, "h": 0.14, "d": 1.6 }, "at": [1.5, 1.5, 1.55], "mat": "oliveDrab", "src": "dossier#mount" },
    { "op": "bevelBox", "id": "fenderRL", "args": { "w": 0.95, "h": 0.14, "d": 1.6 }, "at": [-1.5, 1.5, -1.55], "mat": "oliveDrab", "src": "dossier#mount" },
    { "op": "bevelBox", "id": "fenderRR", "args": { "w": 0.95, "h": 0.14, "d": 1.6 }, "at": [1.5, 1.5, -1.55], "mat": "oliveDrab", "src": "dossier#mount" },

    { "op": "cylinder", "id": "jackFL", "args": { "r": 0.1, "h": 1.15, "axis": "y", "tone": "lo" }, "at": [-1.95, 0.55, 2.35], "mat": "steel", "src": "dossier#mount" },
    { "op": "cylinder", "id": "jackFR", "args": { "r": 0.1, "h": 1.15, "axis": "y", "tone": "lo" }, "at": [1.95, 0.55, 2.35], "mat": "steel", "src": "dossier#mount" },
    { "op": "cylinder", "id": "jackRL", "args": { "r": 0.1, "h": 1.15, "axis": "y", "tone": "lo" }, "at": [-1.95, 0.55, -2.35], "mat": "steel", "src": "dossier#mount" },
    { "op": "cylinder", "id": "jackRR", "args": { "r": 0.1, "h": 1.15, "axis": "y", "tone": "lo" }, "at": [1.95, 0.55, -2.35], "mat": "steel", "src": "dossier#mount" },
    { "op": "cylinder", "id": "jackPadFL", "args": { "r": 0.34, "h": 0.1, "axis": "y" }, "at": [-1.95, 0.05, 2.35], "mat": "oliveDrab", "src": "dossier#mount" },
    { "op": "cylinder", "id": "jackPadFR", "args": { "r": 0.34, "h": 0.1, "axis": "y" }, "at": [1.95, 0.05, 2.35], "mat": "oliveDrab", "src": "dossier#mount" },
    { "op": "cylinder", "id": "jackPadRL", "args": { "r": 0.34, "h": 0.1, "axis": "y" }, "at": [-1.95, 0.05, -2.35], "mat": "oliveDrab", "src": "dossier#mount" },
    { "op": "cylinder", "id": "jackPadRR", "args": { "r": 0.34, "h": 0.1, "axis": "y" }, "at": [1.95, 0.05, -2.35], "mat": "oliveDrab", "src": "dossier#mount" },

    { "op": "cylinder", "id": "turntable", "args": { "r": 1.7, "h": 0.35, "axis": "y" }, "at": [0, 1.55, 0], "mat": "oliveDrab", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "bevelBox", "id": "azMotor",   "args": { "w": 0.45, "h": 0.45, "d": 0.55 }, "at": [0.95, 1.78, 0.85], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "cabinet",  "id": "cabin",     "args": { "w": 3.2, "h": 2.5, "d": 4.0, "panels": 5 }, "at": [0, 2.95, 0], "mat": "oliveDrab", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "bevelBox", "id": "cabinDoor", "args": { "w": 0.9, "h": 1.7, "d": 0.08 }, "at": [1.61, 2.6, 0.4], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "bevelBox", "id": "doorHandle","args": { "w": 0.06, "h": 0.28, "d": 0.08 }, "at": [1.66, 2.6, 0.05], "mat": "steel", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "bevelBox", "id": "cabinWindow","args": { "w": 0.08, "h": 0.5, "d": 0.62 }, "at": [1.61, 3.5, -0.7], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "bevelBox", "id": "ladderStileF", "args": { "w": 0.06, "h": 2.3, "d": 0.06 }, "at": [-1.64, 3.0, 0.3], "mat": "steel", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "bevelBox", "id": "ladderStileR", "args": { "w": 0.06, "h": 2.3, "d": 0.06 }, "at": [-1.64, 3.0, -0.3], "mat": "steel", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "bevelBox", "id": "ladderRung1", "args": { "w": 0.05, "h": 0.05, "d": 0.66 }, "at": [-1.66, 2.2, 0], "mat": "steel", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "bevelBox", "id": "ladderRung2", "args": { "w": 0.05, "h": 0.05, "d": 0.66 }, "at": [-1.66, 2.6, 0], "mat": "steel", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "bevelBox", "id": "ladderRung3", "args": { "w": 0.05, "h": 0.05, "d": 0.66 }, "at": [-1.66, 3.0, 0], "mat": "steel", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "bevelBox", "id": "ladderRung4", "args": { "w": 0.05, "h": 0.05, "d": 0.66 }, "at": [-1.66, 3.4, 0], "mat": "steel", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "bevelBox", "id": "ladderRung5", "args": { "w": 0.05, "h": 0.05, "d": 0.66 }, "at": [-1.66, 3.8, 0], "mat": "steel", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "bevelBox", "id": "ladderRung6", "args": { "w": 0.05, "h": 0.05, "d": 0.66 }, "at": [-1.66, 4.15, 0], "mat": "steel", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "pipe", "id": "grabA", "args": { "r": 0.04, "pts": [[-0.4, 4.22, 1.4], [-0.4, 4.46, 1.4], [0.4, 4.46, 1.4], [0.4, 4.22, 1.4]], "tone": "hi" }, "at": [0, 0, 0], "mat": "steel", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "pipe", "id": "grabB", "args": { "r": 0.04, "pts": [[1.2, 4.22, -0.2], [1.2, 4.46, -0.2], [1.2, 4.46, 0.6], [1.2, 4.22, 0.6]], "tone": "hi" }, "at": [0, 0, 0], "mat": "steel", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "star", "id": "redStar", "args": { "r": 0.45, "axis": "x", "th": 0.06 }, "at": [-1.63, 3.4, 0.95], "mat": "sovietRed", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "cylinder", "id": "tailL", "args": { "r": 0.12, "h": 0.14, "axis": "z", "tone": "bright" }, "at": [-1.0, 1.3, -2.72], "mat": "sovietRed", "src": "dossier#mount" },
    { "op": "cylinder", "id": "tailR", "args": { "r": 0.12, "h": 0.14, "axis": "z", "tone": "bright" }, "at": [1.0, 1.3, -2.72], "mat": "sovietRed", "src": "dossier#mount" },
    { "op": "cylinder", "id": "headL", "args": { "r": 0.13, "h": 0.12, "axis": "z", "tone": "bright" }, "at": [-0.9, 1.4, 2.72], "mat": "missileGrey", "src": "dossier#mount" },
    { "op": "cylinder", "id": "headR", "args": { "r": 0.13, "h": 0.12, "axis": "z", "tone": "bright" }, "at": [0.9, 1.4, 2.72], "mat": "missileGrey", "src": "dossier#mount" },
    { "op": "tubeMast", "id": "mastTower", "args": { "baseW": 1.3, "baseD": 1.3, "h": 3.0, "topW": 0.4, "topD": 0.4, "apexZ": -0.7, "levels": 3, "r": 0.07 }, "at": [0, 4.2, -0.2], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#cabin_base" },

    { "op": "pipe", "id": "armFupL", "args": { "r": 0.06, "pts": [[-0.9, 5.0, -0.1], [-0.9, 4.9, 2.8]], "tone": "mid" }, "at": [0, 0, 0], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "pipe", "id": "armFupR", "args": { "r": 0.06, "pts": [[0.9, 5.0, -0.1], [0.9, 4.9, 2.8]], "tone": "mid" }, "at": [0, 0, 0], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "pipe", "id": "armFloL", "args": { "r": 0.06, "pts": [[-0.9, 4.25, 0.8], [-0.9, 3.3, 2.8]], "tone": "mid" }, "at": [0, 0, 0], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "pipe", "id": "armFloR", "args": { "r": 0.06, "pts": [[0.9, 4.25, 0.8], [0.9, 3.3, 2.8]], "tone": "mid" }, "at": [0, 0, 0], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "pipe", "id": "armRupL", "args": { "r": 0.06, "pts": [[-0.9, 6.4, -1.0], [-0.9, 6.2, -2.0]], "tone": "mid" }, "at": [0, 0, 0], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "pipe", "id": "armRupR", "args": { "r": 0.06, "pts": [[0.9, 6.4, -1.0], [0.9, 6.2, -2.0]], "tone": "mid" }, "at": [0, 0, 0], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "pipe", "id": "armRloL", "args": { "r": 0.06, "pts": [[-0.9, 4.7, -0.6], [-0.9, 5.3, -2.0]], "tone": "mid" }, "at": [0, 0, 0], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "pipe", "id": "armRloR", "args": { "r": 0.06, "pts": [[0.9, 4.7, -0.6], [0.9, 5.3, -2.0]], "tone": "mid" }, "at": [0, 0, 0], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "pipe", "id": "stayL", "args": { "r": 0.05, "pts": [[-0.55, 4.1, -0.5], [-1.35, 1.9, -1.2]], "tone": "lo" }, "at": [0, 0, 0], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#cabin_base" },
    { "op": "pipe", "id": "stayR", "args": { "r": 0.05, "pts": [[0.55, 4.1, -0.5], [1.35, 1.9, -1.2]], "tone": "lo" }, "at": [0, 0, 0], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#cabin_base" },

    { "op": "pipe", "id": "waveguideF", "args": { "r": 0.06, "pts": [[0.7, 1.8, 1.2], [0.6, 2.8, 1.0], [0.45, 3.6, 0.8], [0.3, 4.2, 0.7]], "tone": "hi" }, "at": [0, 0, 0], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#feed_horns" },
    { "op": "pipe", "id": "waveguideR", "args": { "r": 0.06, "pts": [[0.7, 1.8, -0.8], [0.7, 3.0, -0.5], [0.5, 4.2, -0.2], [0.35, 4.8, 0.0]], "tone": "hi" }, "at": [0, 0, 0], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#feed_horns" },

    { "op": "bevelBox", "id": "frontFeedCol", "args": { "w": 0.18, "h": 1.5, "d": 0.18 }, "at": [0, 4.25, 1.15], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#feed_horns" },
    { "op": "cylinder", "id": "fFeed1", "args": { "r": 0.1, "r2": 0.24, "h": 0.42, "axis": "z", "tone": "bright" }, "at": [0, 4.7, 1.35], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#feed_horns" },
    { "op": "cylinder", "id": "fFeed2", "args": { "r": 0.1, "r2": 0.24, "h": 0.42, "axis": "z", "tone": "bright" }, "at": [0, 4.25, 1.35], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#feed_horns" },
    { "op": "cylinder", "id": "fFeed3", "args": { "r": 0.1, "r2": 0.24, "h": 0.42, "axis": "z", "tone": "bright" }, "at": [0, 3.8, 1.35], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#feed_horns" },
    { "op": "bevelBox", "id": "rearFeedCol", "args": { "w": 0.18, "h": 1.4, "d": 0.18 }, "at": [0, 5.35, -0.5], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#feed_horns" },
    { "op": "cylinder", "id": "rFeed1", "args": { "r": 0.26, "r2": 0.11, "h": 0.42, "axis": "z", "tone": "bright" }, "at": [0, 5.7, -0.7], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#feed_horns" },
    { "op": "cylinder", "id": "rFeed2", "args": { "r": 0.26, "r2": 0.11, "h": 0.42, "axis": "z", "tone": "bright" }, "at": [0, 5.25, -0.7], "mat": "gunGrey", "rig": "azimuth", "src": "dossier#feed_horns" },
    { "op": "bevelBox", "id": "rDipoleLine", "args": { "w": 0.06, "h": 1.2, "d": 0.06 }, "at": [0, 4.75, -0.6], "mat": "steel", "rig": "azimuth", "src": "dossier#feed_horns" },

    { "op": "meshReflector", "id": "frontDish", "args": { "w": 9.7, "h": 3.0, "curve": 0.55, "rows": 14, "cols": 12, "seg": 18, "clipTop": 0.42, "clipH": 0.24, "flipZ": true }, "at": [0, 4.0, 2.7], "mat": "steel", "rig": "frontTilt", "src": "dossier#antenna_reflector" },
    { "op": "bevelBox", "id": "frontBack", "args": { "w": 9.3, "h": 0.16, "d": 0.16 }, "at": [0, 4.0, 3.25], "mat": "steel", "rig": "frontTilt", "src": "dossier#derivation" },
    { "op": "meshReflector", "id": "rearDish", "args": { "w": 9.7, "h": 3.0, "curve": 0.55, "rows": 14, "cols": 12, "seg": 18, "clipTop": 0.42, "clipH": 0.24 }, "at": [0, 6.0, -1.6], "mat": "steel", "rig": "rearTilt", "src": "dossier#antenna_reflector" },
    { "op": "bevelBox", "id": "rearBack", "args": { "w": 9.3, "h": 0.16, "d": 0.16 }, "at": [0, 6.0, -2.15], "mat": "steel", "rig": "rearTilt", "src": "dossier#derivation" }
  ]
};
